language: python

python:
  - 2.7
  - 3.4
  - 3.5

install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install pyxb
  - pip install -e .
  - pip install pytest-cov
  - pip install coveralls
  - pip install flake8

before_script:
  - flake8 --count --ignore W503,F401 --exclude teaser/data/bindings,doc,tests --max-line-length=120

script:
  - py.test --cov=teaser

after_success:
  - coveralls
