language: python

python:
  - 2.7
  - 3.4
  - 3.5

install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install pyxb
  - pip install -e .
  - pip install coveralls

script:
  coverage run --source=teaser/logic,teaser/data -m py.test

after_success:
  coveralls
